# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0003_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='contacts',
            field=models.ManyToManyField(related_name='_perfil_contacts_+', to='perfis.Perfil'),
        ),
    ]
